### ISSUE TITLE
unable to evaluate symlinks

### ISSUE THREAD

**Issue by Eskian** [Devidian/docker-spaceengineers#34]
```
Building se-server
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/bshaw/Dockerfile: no such file or directory
ERROR: Service 'se-server' failed to build : Build failed
```

Good evening, and apologies for the newbie question but I keep on getting the above when attempt to run the following .yml code

```
version: "3.8"

services:
  se-server:
    build: .
    image: spaceengineers:latest
    container_name: se-ds-docker
    restart: unless-stopped
    volumes:
      - /space_engineers/instances:/appdata/space-engineers/instances
      - /space_engineers/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - /space_engineers/steamcmd:/root/.steam
    ports:
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment:
      - WINEDEBUG=-all
      - INSTANCE_NAME=Amnesia_se
      - PUBLIC_IP=86.10.191.48
```
