### ISSUE TITLE
SteamCMD not running on macOS (M1)

### ISSUE THREAD

**Issue by lizclipse** [Devidian/docker-spaceengineers#40]
I'm trying to get this to run on my M1 Mac, and there's some odd behaviour. SteamCMD just doesn't seem to run at all, and I'm not familiar enough with it to try and debug it all by myself. I know the config I'm running is correct, since it runs the server just fine on my Linux work machine.

**Comment by Devidian** [comment]
Hi, can you add any log output? I personally never use apple stuff so i dont know if i can help, but i try.

**Comment by lizclipse** [comment]
Whoops, yes that would be helpful, wouldn't it 😅 here is the output from a clean setup and one where I pulled in the SteamCMD and dedicated server folders from the working version. I've also included my config, since I think I've set it up right but I could have missed something. For both of these, the container won't stop, instead it will just hang until I terminate it.

<details>
<summary>Clean install</summary>

```
se-ds-docker  | -------------------------------INSTALL & UPDATE------------------------------
se-ds-docker  | ---------------------------------UPDATE CONFIG-------------------------------
se-ds-docker  | sed: couldn't open temporary file /appdata/space-engineers/instances/CCP/sedMQy2Nt: Permission denied
se-ds-docker  | sed: couldn't open temporary file /appdata/space-engineers/instances/CCP/sedhkKKAy: Permission denied
se-ds-docker  | -----------------------------CURRENT CONFIGURATION---------------------------
se-ds-docker  | GAME_DIR=/appdata/space-engineers/SpaceEngineersDedicated
se-ds-docker  | CONFIG_PATH=/appdata/space-engineers/instances/CCP/SpaceEngineers-Dedicated.cfg
se-ds-docker  | INSTANCE_IP=172.26.0.2
se-ds-docker  | CURRENT_IP=0.0.0.0
se-ds-docker  | CURRENT_WORLDNAME=susvival
se-ds-docker  | SAVE_PATH=Z:\\appdata\\space-engineers\\instances\\CCP\\Saves\\susvival
se-ds-docker  | wine-8.0
se-ds-docker  | ----------------------------------START GAME---------------------------------
se-ds-docker  | rm: cannot remove '/appdata/space-engineers/instances/CCP/*.log': No such file or directory
se-ds-docker  | /root/entrypoint.sh: line 32: cd: /appdata/space-engineers/SpaceEngineersDedicated/DedicatedServer64/: No such file or directory
se-ds-docker  | Application could not be started, or no application associated with the specified file.
se-ds-docker  | ShellExecuteEx failed: File not found.
se-ds-docker  |
```
</details>

<details>
<summary>With pre-filled SteamCMD and DedicatedServer64 directories</summary>

```
se-ds-docker  | -------------------------------INSTALL & UPDATE------------------------------
se-ds-docker  | ---------------------------------UPDATE CONFIG-------------------------------
se-ds-docker  | sed: couldn't open temporary file /appdata/space-engineers/instances/CCP/sed5I2HTw: Permission denied
se-ds-docker  | sed: couldn't open temporary file /appdata/space-engineers/instances/CCP/sediDO0MA: Permission denied
se-ds-docker  | -----------------------------CURRENT CONFIGURATION---------------------------
se-ds-docker  | GAME_DIR=/appdata/space-engineers/SpaceEngineersDedicated
se-ds-docker  | CONFIG_PATH=/appdata/space-engineers/instances/CCP/SpaceEngineers-Dedicated.cfg
se-ds-docker  | INSTANCE_IP=172.27.0.2
se-ds-docker  | CURRENT_IP=0.0.0.0
se-ds-docker  | CURRENT_WORLDNAME=susvival
se-ds-docker  | SAVE_PATH=Z:\\appdata\\space-engineers\\instances\\CCP\\Saves\\susvival
se-ds-docker  | wine-8.0
se-ds-docker  | ----------------------------------START GAME---------------------------------
se-ds-docker  | rm: cannot remove '/appdata/space-engineers/instances/CCP/*.log': No such file or directory
```
</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3.8"

services:
  se-server:
    image: devidian/spaceengineers:latest
    # command: steamcmd
    container_name: se-ds-docker
    restart: unless-stopped
    platform: "linux/amd64"
    volumes:
      # left side: your docker-host machine
      # right side: the paths in the image (!!do not change!!)
      - /Users/liz/Documents/SE/instances:/appdata/space-engineers/instances
      - /Users/liz/Documents/SE/dedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - /Users/liz/Documents/SE/steam:/root/.steam
    ports:
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment:
      WINEDEBUG: "-all"
      INSTANCE_NAME: "CCP"
      PUBLIC_IP: "80.6.228.76"
```
</details>
