### ISSUE TITLE
Local port does not use the one in docker-compose

### ISSUE THREAD

**Issue by Andargor** [Devidian/docker-spaceengineers#45]
In the docker-compose.yml file I have this:

```yaml
    ports:
      - target: 28016
        published: 28016
        protocol: udp
        mode: host
```

But when the server attempts to start it still binds to 27016:

```
2023-04-24 17:57:07.012: Bind IP : 172.22.0.2:27016
```
