### ISSUE TITLE
Unable to load server: Could not load file or assembly 'Sandbox.Game'

### ISSUE THREAD

**Issue by daantimmer** [Devidian/docker-spaceengineers#72]
I've created a TestInstance (yes I did), using the Space Engineers Dedicated Server. Copied the TestInstance folder to where I'll be creating the container from, started it, and then I get the following:
```
PS E:\Space Engineers Docker Server> docker compose up
[+] Running 1/0r Desktop   o View Config   w Enable Watch
 ✔ Container se-ds-docker  Running                                                                                                                                            0.0s 
Attaching to se-ds-docker
se-ds-docker  | OK
se-ds-docker  | Waiting for client config...OK
se-ds-docker  | Waiting for user info...OK                                                                                                                                         
se-ds-docker  | "@sSteamCmdForcePlatformType" = "windows"                                                                                                                          
se-ds-docker  | Success! App '298740' already up to date.                                                                                                                          
se-ds-docker  | ---------------------------------UPDATE CONFIG-------------------------------
se-ds-docker  | ---------------------------------UPDATE PLUGINS------------------------------
se-ds-docker  | ls: cannot access '/appdata/space-engineers/plugins/*.dll': No such file or directory
se-ds-docker  | Found 0 plugins in /appdata/space-engineers/plugins                                                                                                                
se-ds-docker  | -----------------------------CURRENT CONFIGURATION---------------------------                                                                                      
se-ds-docker  | GAME_DIR=/appdata/space-engineers/SpaceEngineersDedicated                                                                                                          
se-ds-docker  | CONFIG_PATH=/appdata/space-engineers/instances/TestInstance/SpaceEngineers-Dedicated.cfg
se-ds-docker  | INSTANCE_IP=172.18.0.2                                                                                                                                             
se-ds-docker  | CURRENT_IP=172.18.0.2                                                                                                                                              
se-ds-docker  | CURRENT_WORLDNAME=Earth Planet                                                                                                                                     
se-ds-docker  | SAVE_PATH=Z:\\appdata\\space-engineers\\instances\\TestInstance\\Saves\\Earth Planet                                                                               
se-ds-docker  | wine-9.9 (Staging)                                                                                                                                                 
se-ds-docker  | ----------------------------------START GAME---------------------------------                                                                                      
se-ds-docker  | rm: cannot remove '/appdata/space-engineers/instances/TestInstance/*.log': No such file or directory
se-ds-docker  |                                                                                                                                                                    
se-ds-docker  | Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Sandbox.Game, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The module was expected to contain an assembly manifest.
se-ds-docker  |    at SpaceEngineersDedicated.MyProgram.Main(String[] args)
se-ds-docker  | wine: Unhandled exception 0xe0434352 in thread 120 at address 00006FFFFF463E67 (thread 0120), starting debugger...                                                 
se-ds-docker  | -----------------------------------END GAME----------------------------------                                                                                      
se-ds-docker  | -----------------------------------BYE !!!!----------------------------------
se-ds-docker exited with code 0
PS E:\Space Engineers Docker Server> 
```

This is my directory tree:
![image](https://github.com/user-attachments/assets/8d523ce7-1d3f-478d-9f3d-296b2fbd1a6f)

And this is the DedicatedServer64 contents, which clearly contains Sandbox.Game.dll:
![image](https://github.com/user-attachments/assets/b3e6c77e-db29-4754-add5-a8ba1496af0e)

Please advice :-)

**Comment by daantimmer** [comment]
```yaml
services:
  se-server:
    image: devidian/spaceengineers:winestaging
    container_name: se-ds-docker
    restart: unless-stopped
    volumes:
      # left side: your docker-host machine
      # right side: the paths in the image (!!do not change!!)
      - ./plugins:/appdata/space-engineers/plugins
      - ./instances:/appdata/space-engineers/instances
      - ./space-engineers/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - ./.steam:/root/.steam
    ports:
      - target: 27016
        published: 27016
        protocol: udp
        mode: host
    environment:
      - WINEDEBUG=-all
      - INSTANCE_NAME=TestInstance
      - PUBLIC_IP=1.2.3.4
      # public ip required for healthcheck
```

forgot to list the docker-compose.yml
