### ISSUE TITLE
Unable to connect to server from outside local network

### ISSUE THREAD

**Issue by Art-Shpiller** [Devidian/docker-spaceengineers#75]
I started the server and can connect from the local network, but not from outside. I’ve opened the ports on the router properly, and I have many other services working externally, so the issue is definitely not with NAT or the firewall. I noticed that the INSTANCE_IP in the log is incorrect—could this be the problem?
INSTANCE_IP is the local IP address of the server and the address of the Docker containers on the server. I also tried setting it up through a virtual network with port forwarding, but it still doesn't work. Could it be that access from outside needs to be configured somewhere in the SpaceEngineers-Dedicated.cfg file?

```
https://api.steampowered.com/ISteamApps/GetServersAtAddress/v1?addr=***.***.***.***
{"response":{"success":true,"servers":[{"addr":"***.***.***.***","gmsindex":-1,"steamid":"90204317197038596","appid":244850,"gamedir":"Space Engineers","region":-1,"secure":true,"lan":false,"gameport":27016,"specport":0}]}}
```
![opera_2024-10-19_12-24-15](https://github.com/user-attachments/assets/28c380d6-e891-40f2-99a5-93d0b09dc7b8)
![Tabby_2024-10-19_12-24-58](https://github.com/user-attachments/assets/3760a90f-d4ee-4958-a318-1904421cf122)

```
services:
  spaceengineers:
    image: devidian/spaceengineers:winestaging
    container_name: spaceengineers
    restart: unless-stopped
    volumes:
      - /docker/space-engineers/config/plugins:/appdata/space-engineers/plugins
      - /docker/space-engineers/instances:/appdata/space-engineers/instances
      - /docker/space-engineers/SpaceEngineersDedicated:/appdata/space-engineers/SpaceEngineersDedicated
      - /docker/space-engineers/steamcmd:/root/.steam
    network_mode: "host"
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - WINEDEBUG=-all
      - INSTANCE_NAME=Adventures
      - PUBLIC_IP=***.***.***.***
```
